name: build_script
description: A sample command-line application.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.4.0

dependencies:
  yaml: ^3.1.3
  http: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
