name: build_script
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.3.0
  crypto: ^3.0.6
  yaml: ^3.1.3
  uuid: ^4.5.1
  path: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

assets:
  - pubspec.yaml