name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Make build directory
        run: mkdir build

      - name: Build executable
        run: dart compile exe bin/main.dart -o build/build_script.exe

      - name: Generate hash
        run: Get-FileHash -Algorithm MD5 build/build_script.exe | Select -ExpandProperty Hash > build/checksum.md5

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Releases
          path: |
            build/build_script.exe
            build/checksum.md5

      - name: Parse pubspec
        uses: martinhaintz/ga-yaml-parser@v0.1.2
        id: read_yaml
        with:
          file: pubspec.yaml

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.read_yaml.outputs['version'] }}
        run: |
          gh release create ${{ env.tag }} --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${{ env.tag }}" --generate-notes build/*
